version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    links:
     - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "order:5:1"
  apache:
    build: apache
    image: kjtully/microservice-kafka-apache:latest
    links:
     - order
     - shipping
     - invoicing
    ports:
     - "8080:80"
  postgres:
    build: postgres
    image: kjtully/microservice-kafka-postgres:latest
    environment:
      POSTGRES_PASSWORD: dbpass
      POSTGRES_USER: dbuser
  order:
    build: ../microservice-kafka/microservice-kafka-order
    image: kjtully/microservice-kafka-order:latest
    links:
     - kafka
     - postgres
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  shipping:
    build: ../microservice-kafka/microservice-kafka-shipping
    image: kjtully/microservice-kafka-shipping:latest
    links:
     - kafka
     - postgres
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  invoicing:
    build: ../microservice-kafka/microservice-kafka-invoicing
    image: kjtully/microservice-kafka-invoicing:latest
    links:
     - kafka
     - postgres
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

